/**
 * Notification type groups and redirect paths for notification click actions.
 * Used by the notification dropdown to navigate users to the correct page.
 */

export const FRIEND_REQUEST_LIST = [
  'NOTIFY_SEND_FRIEND_REQUEST',
  'NOTIFY_ACCEPT_FRIEND_REQUEST',
  'NOTIFY_REJECT_FRIEND_REQUEST',
] as const;

export const POST_NOTIFY_LIST = [
  'NOTIFY_BUDDY_POST',
  'NOTIFY_BUDDY_REQUEST',
  'NOTIFY_BUDDY_REQUEST_ACCEPTED',
  'NOTIFY_BUDDY_REQUEST_REJECTED',
  'NOTIFY_BUDDY_POST_REMINDER',
  'NOTIFY_BUDDY_POST_STARTED',
  'NOTIFY_BUDDY_POST_ENDED',
  'NOTIFY_POST_CREATE',
  'NOTIFY_POST_LIKE',
  'NOTIFY_POST_SHARE',
  'NOTIFY_POST_COMMENT',
  'NOTIFY_FOLLOWERS',
  'NOTIFY_POST_COMMENT_LIKE',
  'NOTIFY_PEOPLE_YOU_MAY_LIKE',
  'NOTIFY_POSTS_YOU_MAY_LIKE',
  'NOTIFY_POST_COMMENT_REPLY',
] as const;

export const TOURNAMENT_NOTIFY_LIST = [
  'NOTIFY_TOURNAMENT_INVITE_AS_COEORGANIZER',
  'NOTIFY_TOURNAMENT_ENDED',
  'NOTIFY_TOURNAMENT_STARTED',
  'NOTIFY_TOURNAMENT_SCORE_UPDATED',
] as const;

export const TRIP_NOTIFY_LIST = [
  'NOTIFY_TRIP_BOOKING_REQUEST',
  'NOTIFY_TRIP_BOOKING_REQUEST_ACCEPT',
  'NOTIFY_TRIP_BOOKING_REQUEST_REJECT',
] as const;

export const COMMUNITY_NOTIFY = [
  'NOTIFY_USER_SEND_COMMUNITY_REQUEST_ACCEPTED',
  'NOTIFY_USER_SEND_COMMUNITY_REQUEST_REJECTED',
  'NOTIFY_USER_SEND_COMMUNITY_EVENT_CREATED',
  'NOTIFY_USER_SEND_COMMUNITY_MEMBER_ADDED',
] as const;

export const COMMUNITY_MANAGE = [
  'NOTIFY_USER_SEND_COMMUNITY_REQUEST',
] as const;

export const COMMUNITY_POST_LIKE = [
  'NOTIFY_USER_SEND_COMMUNITY_POST_LIKE',
  'NOTIFY_USER_SEND_COMMUNITY_UPDATES',
] as const;

/** Base paths for notification redirects (no locale prefix; Link handles that). */
export const NOTIFICATION_REDIRECT_PATHS = {
  /** Friends & requests */
  FRIENDS: '/dashboard/friends',
  FRIEND_REQUESTS: '/dashboard/friends/requests',

  /** Post feed & buddies */
  HOME: '/dashboard',
  BUDDIES: '/dashboard/buddies',

  /** Tournaments */
  TOURNAMENTS_LOCAL: '/dashboard/tournaments/play-local',
  TOURNAMENTS_PRO: '/dashboard/tournaments/pro',

  /** Trips */
  TRIPS: '/dashboard/trips',

  /** Community (placeholder until routes exist) */
  COMMUNITY: '/dashboard',
} as const;

/**
 * Map notification type -> redirect path.
 * Used when content.url is not provided by the API.
 */
export const NOTIFICATION_TYPE_TO_PATH: Record<string, string> = {
  // Friend request list
  NOTIFY_SEND_FRIEND_REQUEST: NOTIFICATION_REDIRECT_PATHS.FRIEND_REQUESTS,
  NOTIFY_ACCEPT_FRIEND_REQUEST: NOTIFICATION_REDIRECT_PATHS.FRIEND_REQUESTS,
  NOTIFY_REJECT_FRIEND_REQUEST: NOTIFICATION_REDIRECT_PATHS.FRIEND_REQUESTS,

  // Post / buddy list – buddy-related to Buddies, rest to Home
  NOTIFY_BUDDY_POST: NOTIFICATION_REDIRECT_PATHS.BUDDIES,
  NOTIFY_BUDDY_REQUEST: NOTIFICATION_REDIRECT_PATHS.BUDDIES,
  NOTIFY_BUDDY_REQUEST_ACCEPTED: NOTIFICATION_REDIRECT_PATHS.BUDDIES,
  NOTIFY_BUDDY_REQUEST_REJECTED: NOTIFICATION_REDIRECT_PATHS.BUDDIES,
  NOTIFY_BUDDY_POST_REMINDER: NOTIFICATION_REDIRECT_PATHS.BUDDIES,
  NOTIFY_BUDDY_POST_STARTED: NOTIFICATION_REDIRECT_PATHS.BUDDIES,
  NOTIFY_BUDDY_POST_ENDED: NOTIFICATION_REDIRECT_PATHS.BUDDIES,
  NOTIFY_POST_CREATE: NOTIFICATION_REDIRECT_PATHS.HOME,
  NOTIFY_POST_LIKE: NOTIFICATION_REDIRECT_PATHS.HOME,
  NOTIFY_POST_SHARE: NOTIFICATION_REDIRECT_PATHS.HOME,
  NOTIFY_POST_COMMENT: NOTIFICATION_REDIRECT_PATHS.HOME,
  NOTIFY_FOLLOWERS: NOTIFICATION_REDIRECT_PATHS.HOME,
  NOTIFY_POST_COMMENT_LIKE: NOTIFICATION_REDIRECT_PATHS.HOME,
  NOTIFY_PEOPLE_YOU_MAY_LIKE: NOTIFICATION_REDIRECT_PATHS.FRIENDS,
  NOTIFY_POSTS_YOU_MAY_LIKE: NOTIFICATION_REDIRECT_PATHS.HOME,
  NOTIFY_POST_COMMENT_REPLY: NOTIFICATION_REDIRECT_PATHS.HOME,

  // Tournament
  NOTIFY_TOURNAMENT_INVITE_AS_COEORGANIZER:
    NOTIFICATION_REDIRECT_PATHS.TOURNAMENTS_LOCAL,
  NOTIFY_TOURNAMENT_ENDED: NOTIFICATION_REDIRECT_PATHS.TOURNAMENTS_LOCAL,
  NOTIFY_TOURNAMENT_STARTED: NOTIFICATION_REDIRECT_PATHS.TOURNAMENTS_LOCAL,
  NOTIFY_TOURNAMENT_SCORE_UPDATED: NOTIFICATION_REDIRECT_PATHS.TOURNAMENTS_LOCAL,

  // Trips
  NOTIFY_TRIP_BOOKING_REQUEST: NOTIFICATION_REDIRECT_PATHS.TRIPS,
  NOTIFY_TRIP_BOOKING_REQUEST_ACCEPT: NOTIFICATION_REDIRECT_PATHS.TRIPS,
  NOTIFY_TRIP_BOOKING_REQUEST_REJECT: NOTIFICATION_REDIRECT_PATHS.TRIPS,

  // Community
  NOTIFY_USER_SEND_COMMUNITY_REQUEST_ACCEPTED:
    NOTIFICATION_REDIRECT_PATHS.COMMUNITY,
  NOTIFY_USER_SEND_COMMUNITY_REQUEST_REJECTED:
    NOTIFICATION_REDIRECT_PATHS.COMMUNITY,
  NOTIFY_USER_SEND_COMMUNITY_EVENT_CREATED:
    NOTIFICATION_REDIRECT_PATHS.COMMUNITY,
  NOTIFY_USER_SEND_COMMUNITY_MEMBER_ADDED:
    NOTIFICATION_REDIRECT_PATHS.COMMUNITY,
  NOTIFY_USER_SEND_COMMUNITY_REQUEST: NOTIFICATION_REDIRECT_PATHS.COMMUNITY,
  NOTIFY_USER_SEND_COMMUNITY_POST_LIKE: NOTIFICATION_REDIRECT_PATHS.COMMUNITY,
  NOTIFY_USER_SEND_COMMUNITY_UPDATES: NOTIFICATION_REDIRECT_PATHS.COMMUNITY,
} as const;

/** Notification types that should open a post detail dialog instead of navigating. */
export const POST_DIALOG_NOTIFICATION_TYPES = new Set([
  'NOTIFY_BUDDY_POST',
  'NOTIFY_BUDDY_REQUEST',
  'NOTIFY_BUDDY_REQUEST_ACCEPTED',
  'NOTIFY_BUDDY_REQUEST_REJECTED',
  'NOTIFY_BUDDY_POST_REMINDER',
  'NOTIFY_BUDDY_POST_STARTED',
  'NOTIFY_BUDDY_POST_ENDED',
  'NOTIFY_POST_CREATE',
  'NOTIFY_POST_LIKE',
  'NOTIFY_POST_SHARE',
  'NOTIFY_POST_COMMENT',
  'NOTIFY_POST_COMMENT_LIKE',
  'NOTIFY_POST_COMMENT_REPLY',
  'NOTIFY_POSTS_YOU_MAY_LIKE',
]);

export interface NotificationForRedirect {
  type: string;
  content?: { url?: string | null };
}

/**
 * Returns the path to redirect to when a notification is clicked.
 * Prefers content.url from the API when present; otherwise uses NOTIFICATION_TYPE_TO_PATH.
 * Returns undefined for unknown types so nothing happens on click.
 */
export function getNotificationRedirectPath(
  notification: NotificationForRedirect
): string | undefined {
  const url = notification.content?.url?.trim();
  if (url && url.startsWith('/')) {
    return url;
  }
  return NOTIFICATION_TYPE_TO_PATH[notification.type];
}
