import React from 'react';
import {
  ArrowDown,
  ArrowUp,
  Bell,
  Bookmark,
  BookmarkX,
  BrainCircuit,
  Building,
  Calendar,
  CarFront,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsUpDown,
  Clock,
  DollarSign,
  Earth,
  Ellipsis,
  EllipsisVertical,
  Eye,
  EyeOff,
  FileText,
  Flag,
  FlagTriangleRight,
  Gauge,
  Globe,
  Goal,
  GraduationCap,
  Handshake,
  Heart,
  HeartHandshake,
  Heater,
  Home,
  IdCard,
  Image,
  Info,
  LandPlot,
  LayoutGrid,
  Lock,
  LogOut,
  Loader,
  Mail,
  MailOpen,
  MapPin,
  Map,
  Medal,
  Megaphone,
  MessageCircle,
  Music,
  Newspaper,
  PaintRoller,
  PanelLeftClose,
  PanelLeftOpen,
  PencilIcon,
  Play,
  Plus,
  RotateCcw,
  Search,
  SendHorizonal,
  Settings,
  Share,
  Smile,
  SquarePen,
  Star,
  StarOff,
  Store,
  Tag,
  Timer,
  Trash,
  Trophy,
  Upload,
  User,
  UserCheck,
  UserCircle,
  UserMinus,
  UserPlus,
  Users,
  UsersIcon,
  Wind,
  X,
  TrashIcon,
  ShieldCheck,
  EditIcon,
  type LucideProps,
  SquareArrowOutUpRight,
  Pause,
  ChevronUp,
  Undo,
  RefreshCcw,
  Signal,
  Compass,
  Share2,
  ScanBarcode,
  Plane,
  TriangleAlert,
} from 'lucide-react';

const IconMap = {
  eye: Eye,
  'eye-off': EyeOff,
  mail: Mail,
  user: User,
  users: Users,
  'user-plus': UserPlus,
  'user-minus': UserMinus,
  'user-check': UserCheck,
  'user-circle': UserCircle,
  'users-round': UsersIcon,
  logout: LogOut,
  search: Search,
  delete: TrashIcon,
  home: Home,
  medal: Medal,
  trophy: Trophy,
  grid: LayoutGrid,
  buddy: HeartHandshake,
  'chevron-right': ChevronRight,
  'chevron-left': ChevronLeft,
  'chevron-down': ChevronDown,
  'chevron-up': ChevronUp,
  'chevron-up-down': ChevronsUpDown,
  'link-arrow': SquareArrowOutUpRight,
  refresh: RefreshCcw,
  undo: Undo,
  info: Info,
  globe: Globe,
  plus: Plus,
  image: Image,
  smile: Smile,
  more: Ellipsis,
  bookmark: Bookmark,
  'bookmark-x': BookmarkX,
  star: Star,
  signal: Signal,
  'star-off': StarOff,
  message: MessageCircle,
  'more-horizontal': EllipsisVertical,
  share: Share,
  share2: Share2,
  heart: Heart,
  'paint-roller': PaintRoller,
  music: Music,
  location: MapPin,
  'map-pin': MapPin,
  map: Map,
  'dollar-sign': DollarSign,
  bin: Trash,
  clock: Clock,
  'land-plot': LandPlot,
  store: Store,
  'graduation-cap': GraduationCap,
  timer: Timer,
  tag: Tag,
  building: Building,
  heater: Heater,
  wind: Wind,
  'car-front': CarFront,
  'id-card': IdCard,
  megaphone: Megaphone,
  earth: Earth,
  handshake: Handshake,
  flag: Flag,
  'golf-flag': FlagTriangleRight,
  gauge: Gauge,
  news: Newspaper,
  'flaged-goal': Goal,
  reset: RotateCcw,
  load: Loader,
  upload: Upload,
  'file-text': FileText,
  close: X,
  send: SendHorizonal,
  'scan-code': ScanBarcode,
  // edit: PencilIcon,
  calendar: Calendar,
  play: Play,
  pause: Pause,
  gpt: BrainCircuit,
  'arrow-up': ArrowUp,
  'arrow-down': ArrowDown,
  write: SquarePen,
  'sheet-left-open': PanelLeftOpen,
  'sheet-left-close': PanelLeftClose,
  check: Check,
  compass: Compass,
  settings: Settings,
  lock: Lock,
  bell: Bell,
  'mail-open': MailOpen,
  edit: EditIcon,
  'shield-check': ShieldCheck,
  Plane,
  'triangle-alert': TriangleAlert,
};

type IconName = keyof typeof IconMap;

export interface IconProps extends LucideProps {
  name: IconName;
}

const Icon: React.FC<IconProps> = ({ name, size = 16, ...props }) => {
  const IconComponent = IconMap[name];
  return <IconComponent size={size} {...props} />;
};

export { Icon };
